version: "3"
services:
  app:
    build: .
    restart: on-failure
    environment:
      - DB_HOST=https://alta-miniproject.cpqktprvxzrp.ap-southeast-2.rds.amazonaws.com
      - DB_USER=admin
      - DB_PASSWORD=qweqwe123
      - DB_DBNAME=alta_miniproject
      - DB_PORT=3306
      - SECRET_JWT=moch
      - CLOUDINARY_CLOUD_NAME=dt3wofhpk
      - CLOUDINARY_API_KEY=285641388143397
      - CLOUDINARY_API_SECRET=hU9H-OriaWup269ZtZOw1QhPcXE
      - CLOUDINARY_UPLOAD_FOLDER=go-cloudinary
    ports:
      - 8082:8082
