package main

import (
	"mini-project-alterra/configs"
	"mini-project-alterra/routes"

	_ "mini-project-alterra/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
)

// @title           Pixelfeed API Documentation
// @version         1.0
// @description     Pixelfeed dibuat untuk memberikan pengguna sebuah platform media sosial yang mudah digunakan dan intuitif, yang memungkinkan mereka untuk berbagi foto mereka dengan orang lain dan untuk mendapatkan umpan balik/komentar dari pengguna lain. Secara keseluruhan, Pixelfeed merupakan sebuah proyek yang dibuat dengan tujuan untuk memberikan sebuah platform media sosial yang mudah digunakan, aman, dan nyaman bagi pengguna untuk berbagi pengalaman mereka melalui foto dan untuk terhubung dengan pengguna lainnya.
// @termsOfService  http://swagger.io/terms/

// @contact.name   Mochammad Hanif
// @contact.url    http://www.github.com/nifz
// @contact.email  ochammadhanif@gmail.com

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      127.0.0.1:8082
// @BasePath  /

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization

// @externalDocs.description  OpenAPI
// @externalDocs.url          https://swagger.io/resources/open-api/
func main() {

	db, err := configs.ConnectDB()
	if err != nil {
		panic(err)
	}

	err = configs.MigrateDB(db)
	if err != nil {
		panic(err)
	}

	e := echo.New()
	routes.New(e, db)
	e.GET("/swagger/*", echoSwagger.WrapHandler)
	e.Logger.Fatal(e.Start(":8082"))
}
