name: Deploy
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: pull-test-deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd mini-project-alterra
            git pull origin main
            go install github.com/swaggo/swag/cmd/swag@latest
            export PATH=$(go env GOPATH)/bin:$PATH
            swag init
            go test -v ./..
            docker-compose down && docker-compose up --build -d
